[package]
name = "rust-blockchain-exercise"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
chrono = "0.4.41"
rust-crypto = "0.2.36"
serde = { version = "1.0.219", features = ["derive"] }
